# Generated by Django 3.1 on 2020-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverification',
            old_name='password',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userverification',
            old_name='username',
            new_name='name',
        ),
    ]
